spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/yuyol/Banking-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D://programming//project//Cloud Native//config"

server:
  port: 8071